# Site settings
title: Translational lymphoma research in the Morin laboratory at Simon Fraser University
lab_name: Morin Laboratory
author: >
  Xiao Sun
institution: HFUT
email: sunx@hfut.edu.cn
description: >
  The MAINLP Laboratory performs Affective Computing and Natural Language Processing
  research using a combination of multimedia in the field of Human-Computer Interaction.
baseurl: ""
url: "https://sxhfut.github.io"
twitter_username: sunxiao
github_username:  sxhfut
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
